WITH TEMP_TABLE AS (
	SELECT AC_POWER, DC_POWER,
	AC_POWER / DC_POWER AS INV_EFFICIENCY,
	EXTRACT(HOUR FROM DATE_TIME) AS UTC_HOUR
	FROM `sql-sandbox-20240505.SolarPower.Generation_Data`
	WHERE PLANT_ID = 4136001 AND DC_POWER <> 0
	ORDER BY INV_EFFICIENCY DESC
)

SELECT UTC_HOUR,
AVG(DC_POWER) AS AVG_DC,
AVG(AC_POWER) AS AVG_AC,
AVG(INV_EFFICIENCY) AS AVG_INV_EFF
FROM TEMP_TABLE
GROUP BY UTC_HOUR
ORDER BY AVG_INV_EFF ASC;
