-- short check
WITH ROWS_TO_UPDATE AS (
  SELECT DC_POWER, AC_POWER, AC_POWER / DC_POWER
  FROM `sql-sandbox-20240505.SolarPower.Generation_Data`
  WHERE PLANT_ID = 4135001 AND DC_POWER > 0
)

SELECT * FROM ROWS_TO_UPDATE;

UPDATE `sql-sandbox-20240505.SolarPower.Generation_Data`
SET DC_POWER = DC_POWER / 10
WHERE PLANT_ID = 4135001 AND DC_POWER > 0
